//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokedexProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokedex1
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Type_1 { get; set; }
        public string Type_2 { get; set; }
        public string Classification { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
        public string Sound { get; set; }
    }
}
